#!/usr/bin/env bash
cd /app/frontend && npm install && npx webpack
ln -s /app/frontend/public /var/www/todosapp.com/html
chown -R www-data:www-data /var/www
chmod -R 755 /var/www
chown -R www-data:www-data /var/www/todosapp.com/html
chmod -R 755 /var/www/todosapp.com/html
nginx
nginx -s reload

cd /app && RAILS_ENV=$RAILS_ENV bundle exec rails db:migrate
cd /app && nohup bundle exec rails s -b '0.0.0.0' > log/development.log 2>&1 &
tail -f /dev/null
